package com.example.marta.battleorganizer_v1.Utils;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.marta.battleorganizer_v1.Utils.Spell;
import com.example.marta.battleorganizer_v1.Utils.Character;

import com.example.marta.battleorganizer_v1.Utils.SpellDao;
import com.example.marta.battleorganizer_v1.Utils.CharacterDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig spellDaoConfig;
    private final DaoConfig characterDaoConfig;

    private final SpellDao spellDao;
    private final CharacterDao characterDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        spellDaoConfig = daoConfigMap.get(SpellDao.class).clone();
        spellDaoConfig.initIdentityScope(type);

        characterDaoConfig = daoConfigMap.get(CharacterDao.class).clone();
        characterDaoConfig.initIdentityScope(type);

        spellDao = new SpellDao(spellDaoConfig, this);
        characterDao = new CharacterDao(characterDaoConfig, this);

        registerDao(Spell.class, spellDao);
        registerDao(Character.class, characterDao);
    }
    
    public void clear() {
        spellDaoConfig.clearIdentityScope();
        characterDaoConfig.clearIdentityScope();
    }

    public SpellDao getSpellDao() {
        return spellDao;
    }

    public CharacterDao getCharacterDao() {
        return characterDao;
    }

}
